### PR TITLE
Add pause/resume functionality

### PR DESCRIPTION
**Pull request by realtaraharris**
This PR adds pause/resume functionality, which is particularly useful for doing Selenium testing on any app relies heavily on `emitonoff`. It makes it easy to "pump" the data layer until the UI is in just the right state to run a given acceptance test without the dreaded `stale element reference: element is not attached to the page document` error that results from re-rendering of elements under test.

This PR also switches the test runner to `tape` only because I found it easier to use. If it helps, I'm happy to switch it back to `mocha`.

TODO:
- [ ] rev version #
- [ ] push to `npm`

cc @konsumer

### CODE REVIEW

**Comment by konsumer** [comment]
Thanks Max! pause/resume is a really good idea, and I imagine will be super-useful in non-testing scenarios, too. I like mocha/chai a bit better, but the difference is pretty minimal (tests read pretty similar) and I like the lighter dependency-graph, so I'm down to switch.

**Comment by konsumer** [comment]
I'll publish to npm tonight.

**Comment by konsumer** [comment]
Added docs in README.md, too. Feel free to PR, if you have more to add.

**Comment by realtaraharris** [comment]
@konsumer one sec, I have another commit to make - it's a minor issue (I want to put underscores on the instance variables so that it's harder for them to collide things - this came up in a place where  there was already an unrelated `.pause` on the object that gets passed in)

**Comment by konsumer** [comment]
No prob! PR away.

**Pull request merged**
